services:
  - type: web
    name: mibyou-diagnosis-frontend
    env: node
    plan: free
    region: singapore
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: ./dist